- name: Start all containers that were stopped during kolla docker daemon restart (pass one - network containers)
  shell: 'docker ps -a  --format "{% raw %}{{.Names}}{% endraw %}" | while read line; do docker start $line; done'
  ignore_errors: true
  become: true

- name: Start all containers that were stopped during kolla docker daemon restart (pass two - all containers)
  shell: 'docker ps -a  --format "{% raw %}{{.Names}}{% endraw %}" | while read line; do docker start $line; done'
  ignore_errors: true
  become: true

- name: Wait for services startup
  wait_for:
    timeout: 120

- name: Set variables
  set_fact:
    testrunner_image: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}/contrail-test:static-centos7-ocata"
    repos_dir: "{{ ansible_env.HOME }}/src/{{ zuul.project.canonical_hostname }}/Juniper"

- name: Reload facts after DHCP address setup
  setup:

- name: Template the testbed.py
  template:
    src: testbed.py.j2
    dest: "{{ ansible_env.HOME}}/testbed.py"

- name: create the directory for VM images
  file:
    path: "{{ repos_dir }}/contrail-test-ci/images"
    state: directory

- name: download the cirros image
  get_url:
    url: "http://{{ docker_registry.fqdn }}/static/cirros-0.3.0-x86_64-disk.vmdk"
    dest: "{{ repos_dir }}/contrail-test-ci/images"

- name: Pull the testrunner image
  docker_image:
    name: "{{ testrunner_image }}"
  become: yes

- name: Run the sanity test
  command: "{{ repos_dir }}/contrail-test-ci/testrunner.sh run -t {{ ansible_env.HOME }}/testbed.py -m {{ repos_dir }} -k /root/.ssh/id_rsa -f ci_sanity '{{ testrunner_image }}'"
  become: yes
  ignore_errors: yes

- name: test the xml report for failures
  shell: "[ x\"$(grep testsuite /root/contrail-test-runs/*/reports/TESTS-TestSuites.xml  | grep -o  'failures=\\S\\+' | uniq)\" = x'failures=\"0\"' ]"
  become: yes
