- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: http://107.170.203.108/logs/

- hosts: all
  roles:
    - contrail-common-libs
    - add-build-sshkey
    - start-zuul-console
    - configure-hosts-entries
    - validate-host
    - repo-sandbox-prepare
