- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: http://107.170.203.108/logs/

- hosts: all
  roles:
    - add-build-sshkey
    - configure-hosts-entries
    - configure-mirrors
    - validate-host
    - prepare-workspace
