- name: "Build binary package for {{ item.name }}"
  shell: |
    rpmbuild \
      --define "_topdir {{ ansible_env.HOME }}/{{ packaging.target_dir }}/" \
      --define "_buildTag {{ packaging.version.distrib }}" \
      --define "_srcVer {{ packaging.version.upstream }}" \
      --define "_skuTag mitaka" \
      {{ item.extra|default('') }} \
      -bb {{ ansible_env.HOME }}/{{ packaging.target_dir }}/tools/packaging/common/rpm/{{ item.name }}.spec
  args:
    chdir: "{{ ansible_env.HOME }}/{{ packaging.target_dir }}/{{ item.workdir|default('') }}"

