- hosts: all
  pre_tasks:
    - name: Install build dependencies
      package:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - centos-release-openstack-ocata
    - name: Install build dependencies
      package:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - python2-requests
  roles:
    - role: contrail-ansible-deployer
      cloud_orchestrator: openstack
      openstack_version: ocata
    - role: kolla-provision-dockers
      kolla_provision_dir: '/tmp/contrail-kolla-ansible'
      kolla_config_dir: "{{ kolla_provision_dir }}/etc/kolla"
      kolla_docker_distro: "ubuntu"
      openstack_version: "ocata"
      kolla_version: "contrail_4_1_8"
    - contrail-sanitytests
